function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1; // obj_player
	global.__objectDepths[1] = -1; // obj_ship
	global.__objectDepths[2] = -1; // obj_ball
	global.__objectDepths[3] = -1; // obj_ufo
	global.__objectDepths[4] = -1; // obj_wave
	global.__objectDepths[5] = 0; // obj_wall
	global.__objectDepths[6] = -135407305; // obj_ground
	global.__objectDepths[7] = -135407305; // obj_ground2
	global.__objectDepths[8] = 0; // obj_grid1
	global.__objectDepths[9] = 0; // obj_grid2
	global.__objectDepths[10] = 0; // obj_grid3
	global.__objectDepths[11] = 0; // obj_grid4
	global.__objectDepths[12] = 0; // obj_grid5
	global.__objectDepths[13] = 0; // obj_grid6
	global.__objectDepths[14] = 0; // obj_grid7
	global.__objectDepths[15] = 0; // obj_grid8
	global.__objectDepths[16] = 0; // obj_tile1
	global.__objectDepths[17] = 0; // obj_tile2
	global.__objectDepths[18] = 0; // obj_tile3
	global.__objectDepths[19] = 0; // obj_tile4
	global.__objectDepths[20] = 0; // obj_tile5
	global.__objectDepths[21] = 0; // obj_tile6
	global.__objectDepths[22] = 0; // obj_tile7
	global.__objectDepths[23] = 0; // obj_regular_platform
	global.__objectDepths[24] = 0; // obj_spike1
	global.__objectDepths[25] = 0; // obj_spike2
	global.__objectDepths[26] = 0; // obj_floor_spike
	global.__objectDepths[27] = 0; // obj_player_deadbox
	global.__objectDepths[28] = 0; // obj_restart
	global.__objectDepths[29] = 420420420; // obj_camera
	global.__objectDepths[30] = 0; // obj_ring_par
	global.__objectDepths[31] = 0; // obj_portal_par
	global.__objectDepths[32] = 0; // obj_trigger_par
	global.__objectDepths[33] = 0; // obj_button_par
	global.__objectDepths[34] = 0; // obj_win_wall
	global.__objectDepths[35] = 0; // obj_level_handler
	global.__objectDepths[36] = 0; // obj_pad1
	global.__objectDepths[37] = 0; // obj_pad2
	global.__objectDepths[38] = 0; // obj_pad3
	global.__objectDepths[39] = 0; // obj_pad4
	global.__objectDepths[40] = 0; // obj_ring1
	global.__objectDepths[41] = 0; // obj_ring2
	global.__objectDepths[42] = 0; // obj_ring3
	global.__objectDepths[43] = 0; // obj_ring4
	global.__objectDepths[44] = 0; // obj_ring5
	global.__objectDepths[45] = 0; // obj_speed0
	global.__objectDepths[46] = 0; // obj_speed1
	global.__objectDepths[47] = 0; // obj_speed2
	global.__objectDepths[48] = 0; // obj_speed3
	global.__objectDepths[49] = 0; // obj_portal_normal_grav
	global.__objectDepths[50] = 0; // obj_portal_invert_grav
	global.__objectDepths[51] = 0; // obj_cube_portal
	global.__objectDepths[52] = 0; // obj_ship_portal
	global.__objectDepths[53] = 0; // obj_ball_portal
	global.__objectDepths[54] = 0; // obj_ufo_portal
	global.__objectDepths[55] = 0; // obj_wave_portal
	global.__objectDepths[56] = 0; // obj_robot_portal
	global.__objectDepths[57] = 0; // obj_spider_portal
	global.__objectDepths[58] = 0; // obj_nomini_portal
	global.__objectDepths[59] = 0; // obj_mini_portal
	global.__objectDepths[60] = 0; // obj_par1
	global.__objectDepths[61] = 0; // obj_par2
	global.__objectDepths[62] = 0; // obj_par3
	global.__objectDepths[63] = 0; // obj_trigger_bgcol
	global.__objectDepths[64] = 0; // obj_trigger_gcol
	global.__objectDepths[65] = 0; // obj_top_btn_back
	global.__objectDepths[66] = 0; // obj_title_deco_line
	global.__objectDepths[67] = 0; // obj_level_shield
	global.__objectDepths[68] = 1; // obj_level_exp_bar
	global.__objectDepths[69] = 0; // obj_textfield
	global.__objectDepths[70] = 0; // obj_draw_title
	global.__objectDepths[71] = 1; // obj_negrito
	global.__objectDepths[72] = 0; // obj_title_popup
	global.__objectDepths[73] = 0; // obj_title
	global.__objectDepths[74] = 0; // o_gui_home_ranking
	global.__objectDepths[75] = 0; // o_gui_home_mission
	global.__objectDepths[76] = 0; // o_gui_home_reward
	global.__objectDepths[77] = 0; // o_gui_home_daily
	global.__objectDepths[78] = 0; // o_gui_home_friends
	global.__objectDepths[79] = 0; // o_gui_home_dungeons
	global.__objectDepths[80] = 0; // o_gui_home_store
	global.__objectDepths[81] = 0; // o_gui_home_inventory
	global.__objectDepths[82] = 0; // o_gui_home_guild
	global.__objectDepths[83] = 0; // o_gui_home_heroes
	global.__objectDepths[84] = 1; // obj_home_menu_btn
	global.__objectDepths[85] = 1; // obj_home_minibtns_helper
	global.__objectDepths[86] = 0; // obj_home_elder
	global.__objectDepths[87] = 0; // obj_home_play
	global.__objectDepths[88] = 0; // obj_home_join_world
	global.__objectDepths[89] = 0; // obj_levelsel_frame


	global.__objectNames[0] = "obj_player";
	global.__objectNames[1] = "obj_ship";
	global.__objectNames[2] = "obj_ball";
	global.__objectNames[3] = "obj_ufo";
	global.__objectNames[4] = "obj_wave";
	global.__objectNames[5] = "obj_wall";
	global.__objectNames[6] = "obj_ground";
	global.__objectNames[7] = "obj_ground2";
	global.__objectNames[8] = "obj_grid1";
	global.__objectNames[9] = "obj_grid2";
	global.__objectNames[10] = "obj_grid3";
	global.__objectNames[11] = "obj_grid4";
	global.__objectNames[12] = "obj_grid5";
	global.__objectNames[13] = "obj_grid6";
	global.__objectNames[14] = "obj_grid7";
	global.__objectNames[15] = "obj_grid8";
	global.__objectNames[16] = "obj_tile1";
	global.__objectNames[17] = "obj_tile2";
	global.__objectNames[18] = "obj_tile3";
	global.__objectNames[19] = "obj_tile4";
	global.__objectNames[20] = "obj_tile5";
	global.__objectNames[21] = "obj_tile6";
	global.__objectNames[22] = "obj_tile7";
	global.__objectNames[23] = "obj_regular_platform";
	global.__objectNames[24] = "obj_spike1";
	global.__objectNames[25] = "obj_spike2";
	global.__objectNames[26] = "obj_floor_spike";
	global.__objectNames[27] = "obj_player_deadbox";
	global.__objectNames[28] = "obj_restart";
	global.__objectNames[29] = "obj_camera";
	global.__objectNames[30] = "obj_ring_par";
	global.__objectNames[31] = "obj_portal_par";
	global.__objectNames[32] = "obj_trigger_par";
	global.__objectNames[33] = "obj_button_par";
	global.__objectNames[34] = "obj_win_wall";
	global.__objectNames[35] = "obj_level_handler";
	global.__objectNames[36] = "obj_pad1";
	global.__objectNames[37] = "obj_pad2";
	global.__objectNames[38] = "obj_pad3";
	global.__objectNames[39] = "obj_pad4";
	global.__objectNames[40] = "obj_ring1";
	global.__objectNames[41] = "obj_ring2";
	global.__objectNames[42] = "obj_ring3";
	global.__objectNames[43] = "obj_ring4";
	global.__objectNames[44] = "obj_ring5";
	global.__objectNames[45] = "obj_speed0";
	global.__objectNames[46] = "obj_speed1";
	global.__objectNames[47] = "obj_speed2";
	global.__objectNames[48] = "obj_speed3";
	global.__objectNames[49] = "obj_portal_normal_grav";
	global.__objectNames[50] = "obj_portal_invert_grav";
	global.__objectNames[51] = "obj_cube_portal";
	global.__objectNames[52] = "obj_ship_portal";
	global.__objectNames[53] = "obj_ball_portal";
	global.__objectNames[54] = "obj_ufo_portal";
	global.__objectNames[55] = "obj_wave_portal";
	global.__objectNames[56] = "obj_robot_portal";
	global.__objectNames[57] = "obj_spider_portal";
	global.__objectNames[58] = "obj_nomini_portal";
	global.__objectNames[59] = "obj_mini_portal";
	global.__objectNames[60] = "obj_par1";
	global.__objectNames[61] = "obj_par2";
	global.__objectNames[62] = "obj_par3";
	global.__objectNames[63] = "obj_trigger_bgcol";
	global.__objectNames[64] = "obj_trigger_gcol";
	global.__objectNames[65] = "obj_top_btn_back";
	global.__objectNames[66] = "obj_title_deco_line";
	global.__objectNames[67] = "obj_level_shield";
	global.__objectNames[68] = "obj_level_exp_bar";
	global.__objectNames[69] = "obj_textfield";
	global.__objectNames[70] = "obj_draw_title";
	global.__objectNames[71] = "obj_negrito";
	global.__objectNames[72] = "obj_title_popup";
	global.__objectNames[73] = "obj_title";
	global.__objectNames[74] = "o_gui_home_ranking";
	global.__objectNames[75] = "o_gui_home_mission";
	global.__objectNames[76] = "o_gui_home_reward";
	global.__objectNames[77] = "o_gui_home_daily";
	global.__objectNames[78] = "o_gui_home_friends";
	global.__objectNames[79] = "o_gui_home_dungeons";
	global.__objectNames[80] = "o_gui_home_store";
	global.__objectNames[81] = "o_gui_home_inventory";
	global.__objectNames[82] = "o_gui_home_guild";
	global.__objectNames[83] = "o_gui_home_heroes";
	global.__objectNames[84] = "obj_home_menu_btn";
	global.__objectNames[85] = "obj_home_minibtns_helper";
	global.__objectNames[86] = "obj_home_elder";
	global.__objectNames[87] = "obj_home_play";
	global.__objectNames[88] = "obj_home_join_world";
	global.__objectNames[89] = "obj_levelsel_frame";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
